CLIENT_ID = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
CLIENT_SECRET = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
USER_NAME = "xxxx@xxxx.xxxx"
PASSWORD = "xxxxxxxx"
LOGIN_URL = "https://login.salesforce.com"
MY_DOMAIN = "mydomain.my.salesforce.com"
JWT_HEADER = "{\"alg\":\"RS256\"}"
